# Generated by Django 4.2.2 on 2023-06-13 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=100)),
                ('author_name', models.CharField(max_length=100)),
                ('song', models.FileField(upload_to='songs/')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='music.categories')),
            ],
        ),
    ]
