# Generated by Django 4.2.2 on 2023-07-18 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='music',
            options={'verbose_name': 'Музыка'},
        ),
    ]
